# Generated by Django 6.0.5 on 2026-06-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_artist_alter_song_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.ImageField(default=1, upload_to='songs/'),
            preserve_default=False,
        ),
    ]
